= WPS 2.0 Conformance Test Suite

== Scope

This executable test suite (ETS) verifies the conformance of the implementation
under test (IUT) with respect to the set of relevant specifications depicted in
Figure 1. Conformance testing is a kind of "black box" testing that examines the
externally visible characteristics or behaviors of the IUT while disregarding
any implementation details.

The test suite evaluates compliance of an implementation to:

* WPS 2.0.2 Interface Standard Corrigendum 2 (OGC 14-065r2)

Support for the following conformance classes is tested:

* Basic WPS 
* Synchronous WPS 
* Asynchronous WPS

To quality for Compliance certification, a product has to:

* Pass both the Basic and Synchronous WPS tests, or
* Pass both the Basic and Asynchronous WPS tests

== Test requirements

The documents listed below stipulate requirements that must be satisfied by a 
conforming implementation.

1. http://docs.opengeospatial.org/is/14-065/14-065.html[WPS 2.0.2 Interface Standard Corrigendum 2]

If any of the following preconditions are not satisfied then all tests in the
suite will be marked as skipped.

1. Precondition. Verify that the server can handle echo process.

== Test suite structure

The test suite definition file (testng.xml) is located in the root package, 
`org.opengis.cite.wps20`. A conformance class corresponds to a &lt;test&gt; element, each
of which includes a set of test classes that contain the actual test methods. 
The general structure of the test suite is shown in Table 1.

.Test suite structure
[cols="2,6a",options=header]
|===
|Conformance class
|Test classes

|Conformance Level 1
|org.opengis.cite.wps20.level1.*

|===

The Javadoc documentation provides more detailed information about the test 
methods that constitute the suite.

include::how-to-run-the-tests.adoc[]

== Using the REST API

Using the REST API of the TEAM Engine requires some run arguments. These ate summarized in Table 2.
The _Obligation_ descriptor can have the following values: M (mandatory), O (optional), or C (conditional).

.Test run arguments
[cols="1,1,1,6",options=header]
|===
|Name
|Value domain
|Obligation
|Description

|IUT
|URI
|M
|A URI that refers to the implementation under test or metadata about it. Ampersand ('&amp;') characters must be percent-encoded as '%26'.

|SERVICE_URL
|URI
|M
|A URI that refers to the implementation under test or metadata about it. Ampersand ('&amp;') characters must be percent-encoded as '%26'. Currently simply set this argument the same value with IUT.

|ECHO_PROCESS_ID
|A string value.
|M
|A string that refers to the echo process id implemented by the service.

|===
